monEtab/src/connexion/urls.py
from django.urls import path
from .views import sign_in, sign_up, log_out


app_name = 'connexion'
urlpatterns = [
    path('',sign_in, name='sign_in'),
    path('sign_up/', sign_up, name='sign_up'),
    path('log_out/', log_out, name='log_out')
]

monEtab/src/report/urls.py
from django.urls import  path
from . import views

app_name="report"
urlpatterns = [
   path('', views.index, name="index"),
]

monEtab/src/student/urls.py
from django.urls import  path
from .views import list, add, update, supprimerStudent

app_name= "student"
urlpatterns = [
   path('', list, name="list"),
   path('add/', add, name="add" ),  
   path('modifierStudent/<int:id>', update, name="modifierStudent" ),
   path('supprimerStudent/<int:id>', supprimerStudent, name="supprimerStudent")
]

monEtab/src/teacher/urls.py
from django.urls import  path
from . import views

app_name="teacher"
urlpatterns = [
   path('', views.list, name="list"),
   path('add/', views.add, name='add' ),
   path('modifierTeacher/<int:id>', views.modifierTeacher, name='modifierTeacher' ),
   path('supprimerTacher/<int:id>',views.supprimerTeacher, name='supprimerTeacher')
]

monEtab/src/user/urls.py
from django.urls import  path
from . import views

app_name="user"

urlpatterns = [
   path('', views.list, name="list"),
   path('add/', views.add, name='add' ),
   path('update/<int:id>', views.update, name='update'),
   path('delete/<int:id>', views.delete, name='delete'),
]

monEtab/src/website/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/',include('student.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('teacher/',include('teacher.urls')),
    path('user/',include('user.urls')),
    path('report/',include('report.urls')),
    path('connexion/',include('connexion.urls')),
]

monEtab/src/templates/acceuil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% csrf_token %}
    <h1> Bienvenu </h1>
</body>
</html>

monEtab/src/templates/addStudent.html
{% extends 'base.html' %}

{% block content %}

<header>
    <h1>Ajouter un Élève</h1>
    <a href="{% url 'student:list' %}">
        <button>Retour</button>
    </a>
</header>

<div class="form-container">
    <h2>Formulaire d'ajout d'élève</h2>
    <form method="POST" id="add-student-form" class="add-student-form">
        {% csrf_token %}
        {{ student_form }}
        <div class="form-actions">
            <input type="submit" value="Enregistrer">
            <input type="reset" value="Annuler">
        </div>
        <div class="form-message" id="form-message"></div>
    </form>
</div>

{% endblock content %}

monEtab/src/templates/addTeacher.html
{% extends 'base.html' %}

{% block content %}

<header>
    <h1>Ajouter Professeurs</h1>
    <a href="{% url 'teacher:list' %}">
        <button>Retour</button>
    </a>
</header>

<div class="form-container">
    <h2>Formulaire d'ajout professeurs</h2>
    <form method="POST" id="add-prof-form">
        {% csrf_token %}
        {{ teacher_form }}
        <div class="form-actions">
            <input type="submit" value="Enregistrer">
            <input type="reset" value="Annuler">
        </div>
        <div class="form-message" id="form-message"></div>
    </form>
</div>

{% endblock content %}

monEtab/src/templates/addUser.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<header>
    <h1>Ajouter un Utilisateur</h1>
    <a href="{% url 'user:list' %}">
        <button>Retour</button>
    </a>
</header>

<div class="form-container">
    <h2>Formulaire d'Ajout</h2>
    <form method="POST" id="add-user-form">
        {% csrf_token %}
        {{ user_form }}
                       
        <div class="form-actions">
            <input type="submit" value="Enregistrer">
            <input type="reset" value="Annuler">
        </div>
        <div class="form-message" id="form-message"></div>
    </form>
</div>

{% endblock content %}

monEtab/src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liste des Utilisateurs</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
    <div class="sidebar">
        <img src="image.avif" alt="Logo de l'Établissement">
        <h2>Menu</h2>
        <ul>
            <li><a href="{% url 'dashboard:index' %}">Dashboard</a></li>
            <li><a href="{% url 'student:list' %}">Élèves</a></li>
            <li><a href="{% url 'teacher:list' %}">Professeurs</a></li>
            <li><a href="{% url 'user:list' %}">Utilisateurs</a></li>
            <li><a href="{% url 'report:index' %}">Rapports</a></li>
        </ul>
       <a href="{% url 'connexion:log_out' %}">
        <div class="logout-button" onclick="logout()">Se déconnecter</div>
       </a>
    </div>

    <div class="main-content">
        {% block content %}
        {% endblock content %}
    </div>

</body>
</html>

monEtab/src/templates/listStudent.html
{% extends 'base.html' %}

{% block content %}


<style>

    /* Styles pour le pop-up */
    .popup-overlay {
        display: none; /* Masqué par défaut */
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.5); /* Couleur de l'overlay */
        z-index: 1000; /* Au-dessus du contenu */
        justify-content: center;
        align-items: center;
    }
    
    .popup-content {
        background: white;
        padding: 20px;
        border-radius: 5px;
        text-align: center;
        position: relative; /* Positionnement relatif pour le pop-up */
        z-index: 1001; /* Au-dessus de l'overlay */
    }
    
    /* Appliquer le flou uniquement à l'arrière-plan */
    .blur {
        filter: blur(5px);
        position: relative;
        z-index: 999; /* Sous le pop-up */
    }
        
        
    </style>


<header>
    <h1>Liste des Élèves</h1>
    <a href="{% url 'student:add' %}">
        <button class="add-button">Nouvel Élève</button>
    </a>
    <a href="{% url 'dashboard:index' %}">
        <button class="add-button"> Retour </button>
    </a>
</header>

<table>
    <thead>
        <tr>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Classe</th>
            <th>Matricule</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for student in students %}
            <tr>
                <td> {{ student.first_name }} </td>
                <td> {{ student.last_name }} </td>
                <td> {{ student.class_student }} </td>
                <td> {{ student.register_number }} </td>
                <td class="action-buttons">
                    <a href="{% url 'student:modifierStudent' student.id %}">
                        <button class="edit-button">Update</button>
                    </a>
                    <a href="{% url 'student:supprimerStudent' student.id %}" id="deleteLink" >
                        <button class="delete-button" onclick="confirmDelete(1)">supprimer</button>
                    </a>
                </td>
            </tr>
        {% endfor %}
        <!-- Ajoutez plus de lignes ici -->
    </tbody>
</table>

<div id="confirmationPopup" class="popup-overlay">
    <div class="popup-content">
        <p>Êtes-vous sûr de vouloir supprimer cet élément ?</p>
        <button id="confirmButton">Oui</button>
        <button id="cancelButton">Non</button>
    </div>
</div>

<script>
    
    function confirmDelete() {
    // Prévenir le comportement par défaut du lien
    event.preventDefault();

    // Obtenir les éléments
    const popupOverlay = document.getElementById('confirmationPopup');
    const body = document.body;
    const deleteLink = document.getElementById('deleteLink');

    // Afficher le pop-up
    popupOverlay.style.display = 'flex'; // Affiche le pop-up
    //body.classList.add('blur'); // Applique le flou à l'arrière-plan

    // Gérer les boutons de confirmation
    document.getElementById('confirmButton').onclick = function() {
        body.classList.remove('blur'); // Retirer le flou
        popupOverlay.style.display = 'none'; // Masquer le pop-up
        window.location.href = deleteLink.href; // Rediriger vers l'URL de suppression
    };

    document.getElementById('cancelButton').onclick = function() {
        popupOverlay.style.display = 'none'; // Masquer le pop-up
        //body.classList.remove('blur'); // Retirer le flou
    };
}


</script>


{% endblock content %}

monEtab/src/templates/listTeacher.html
{% extends 'base.html' %}

{% block content %}

<style>

.popup-overlay {
    display: none; /* Masqué par défaut */
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.5); /* Couleur de l'overlay */
    z-index: 1000; /* Au-dessus du contenu */
    justify-content: center;
    align-items: center;
}

.popup-content {
    background: white;
    padding: 20px;
    border-radius: 5px;
    text-align: center;
}

.popup-content button {
    margin: 10px;
}

/* Flouter l'arrière-plan */
.blur {
    filter: blur(5px);
}

</style>


<header>
    <h1>Liste des Professeurs</h1>
    <a href="{% url 'teacher:add' %}">
        <button class="add-button">Nouveau professeur</button>
    </a>
    <a href="{% url 'dashboard:index' %}">
        <button class="add-button"> Retour </button>
    </a>
</header>

<table>
    <thead>
        <tr>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Ville</th>
            <th>Telephone</th>
            <th>Vacant</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for teacher in teachers %}
            <tr id="prof-1">
                <td> {{ teacher.first_name }} </td>
                <td> {{ teacher.last_name }} </td>
                <td> {{ teacher.city }} </td>
                <td> {{ teacher.number }} </td>
                <td> {{ teacher.vacation }} </td>
                <td class="action-buttons">
                    <a href="{% url 'teacher:modifierTeacher' teacher.id  %}">
                        <button class="edit-button">Update</button>
                    </a>
                    <a href="{% url 'teacher:supprimerTeacher' teacher.id  %}" id="deleteLink" >
                        <button class="delete-button" onclick="confirmDelete(1)">supprimer</button>
                    </a>   
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Pop-up de confirmation -->
<div id="confirmationPopup" class="popup-overlay">
    <div class="popup-content">
        <p>Êtes-vous sûr de vouloir supprimer cet élément ?</p>
        <button id="confirmButton">Oui</button>
        <button id="cancelButton">Non</button>
    </div>
</div>

<script>
    
    function confirmDelete() {
    // Prévenir le comportement par défaut du lien
    event.preventDefault();

    // Obtenir les éléments
    const popupOverlay = document.getElementById('confirmationPopup');
    const body = document.body;
    const deleteLink = document.getElementById('deleteLink');

    // Afficher le pop-up
    popupOverlay.style.display = 'flex'; // Affiche le pop-up
    //body.classList.add('blur'); // Applique le flou à l'arrière-plan

    // Gérer les boutons de confirmation
    document.getElementById('confirmButton').onclick = function() {
        body.classList.remove('blur'); // Retirer le flou
        popupOverlay.style.display = 'none'; // Masquer le pop-up
        window.location.href = deleteLink.href; // Rediriger vers l'URL de suppression
    };

    document.getElementById('cancelButton').onclick = function() {
        popupOverlay.style.display = 'none'; // Masquer le pop-up
        //body.classList.remove('blur'); // Retirer le flou
    };
}


</script>

{% endblock content %}

monEtab/src/templates/listUser.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<style>

/* Styles pour le pop-up */
.popup-overlay {
    display: none; /* Masqué par défaut */
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.5); /* Couleur de l'overlay */
    z-index: 1000; /* Au-dessus du contenu */
    justify-content: center;
    align-items: center;
}

.popup-content {
    background: white;
    padding: 20px;
    border-radius: 5px;
    text-align: center;
    position: relative; /* Positionnement relatif pour le pop-up */
    z-index: 1001; /* Au-dessus de l'overlay */
}

/* Appliquer le flou uniquement à l'arrière-plan */
.blur {
    filter: blur(5px);
    position: relative;
    z-index: 999; /* Sous le pop-up */
}
    
    
</style>

<header>
    <h1>Liste des Utilisateurs</h1>
    <a href="{% url 'connexion:sign_up' %}">
        <button class="add-button">Nouvel utilisateurs</button>
    </a>
    <a href="{% url 'dashboard:index' %}">
        <button class="add-button"> Retour </button>
    </a>
    <a href="{% url 'connexion:log_out' %}">
        <button class="add-button"> log out </button>
    </a>
</header>

<div class="user-list-container">
    <h2>Utilisateurs</h2>
    <table>
        <thead>
            <tr>
                <th>Pseudo</th>
                <th>Date de Création</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody id="user-list">
            {% for user in users %}
                <tr>
                    <td> {{ user.id }} </td>
                    <td> {{ user.username }} </td>
                    <td>
                        <a href="{% url 'user:update' user.id %}">Modifier</a>
                        <a href="{% url 'user:delete' user.id %}" id="deleteLink" >
                            <button class="delete-button" onclick="confirmDelete(1)">supprimer</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div id="confirmationPopup" class="popup-overlay">
    <div class="popup-content">
        <p>Êtes-vous sûr de vouloir supprimer cet élément ?</p>
        <button id="confirmButton">Oui</button>
        <button id="cancelButton">Non</button>
    </div>
</div>

<script>
    
    function confirmDelete() {
    // Prévenir le comportement par défaut du lien
    event.preventDefault();

    // Obtenir les éléments
    const popupOverlay = document.getElementById('confirmationPopup');
    const body = document.body;
    const deleteLink = document.getElementById('deleteLink');

    // Afficher le pop-up
    popupOverlay.style.display = 'flex'; // Affiche le pop-up
    //body.classList.add('blur'); // Applique le flou à l'arrière-plan

    // Gérer les boutons de confirmation
    document.getElementById('confirmButton').onclick = function() {
        body.classList.remove('blur'); // Retirer le flou
        popupOverlay.style.display = 'none'; // Masquer le pop-up
        window.location.href = deleteLink.href; // Rediriger vers l'URL de suppression
    };

    document.getElementById('cancelButton').onclick = function() {
        popupOverlay.style.display = 'none'; // Masquer le pop-up
        //body.classList.remove('blur'); // Retirer le flou
    };
}


</script>

{% endblock %}

monEtab/src/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authentification</title>
    <link rel="stylesheet" href="{% static 'css/auth.css' %}">
</head>
<body>
    <div class="auth-container">
        <h1>Mon Etab</h1>

        <form method="POST" id="loginForm" enctype="multipart/form-data">
            {% csrf_token %} 
            <input type="hidden" name="text" value="{{ next }}">
            {% if error_message %}
                <p style="color: red;" > {{ error_message }} </p>
            {% endif %}
            <div class="input-group">
                <label for="pseudo">Pseudo</label>
                <input type="text" id="pseudo" name="username" required>
            </div>
            <div class="input-group">
                <label for="motdepasse">Mot de Passe</label>
                <input type="password" id="motdepasse" name="password" required>
            </div>
            <button type="submit">Se Connecter</button>
            <p>
                vous n'avez de compte cliquez <a href="{% url 'connexion:sign_up' %}">Ici</a>
            </p>
        </form>
    </div>
    <script src="{% static 'auth.js' %}"></script>
</body>
</html>

monEtab/src/templates/register.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authentification</title>
    <link rel="stylesheet" href="{% static 'css/auth.css' %}">
</head>
<body>
    <div class="auth-container">
        <h1>S'inscrire</h1>
        <form method="POST" id="loginForm">
            {% csrf_token %}
            <div class="input-group">
                <label for="pseudo">Pseudo</label>
                <input type="text" id="pseudo" name="pseudo" required>
            </div>
            <div class="input-group">
                <label for="motdepasse">Mot de Passe</label>
                <input type="password" id="motdepasse" name="pwd" required>
            </div>
            <button type="submit">Se Connecter</button>
        </form>
    </div>
    <script src="{% static 'auth.js' %}"></script>
</body>
</html>

monEtab/src/templates/updateStudent.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


<header>
    <h1>Modifier un Élève</h1>
</header>

<div class="form-container">
    <h2>Formulaire de modification des elèves</h2>
    <form method="post" id="add-student-form" class="add-student-form">
        {% csrf_token %}
        {{ student_form }}
        
        <div class="form-actions">
            <button type="submit" class="save-button">Enregistrer</button>
            <button type="button" class="cancel-button" onclick="cancel()">Annuler</button>
        </div>
        <div class="form-message" id="form-message"></div>
    </form>
</div>


{% endblock content %}

monEtab/src/templates/updateTeacher.html
{% extends 'base.html' %}

{% block content %}

<header>
    <h1>Modifier Professeurs</h1>
</header>

<div class="form-container">
    <h2>Formulaire de modification professeurs</h2>
    <form method="post" id="add-prof-form">
        {% csrf_token %}
        {{ teacher_form }}
        
        <br>
        
        <div class="form-actions">
            <button type="submit" class="save-button">Enregistrer</button>
            <button type="button" class="cancel-button" onclick="cancel()">Annuler</button>
        </div>
        <div class="form-message" id="form-message"></div>
    </form>
</div>
{% endblock content %}

monEtab/src/templates/updateUser.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<header>
    <h1>Modifier l'utilisateur</h1>
</header>

<div class="form-container">
    <h2>Formulaire de modification de l'utilisateur</h2>
    <form method="post" id="add-prof-form">
        {% csrf_token %}
        {{ user_form }}
        
        <br>
        
        <div class="form-actions">
            <button type="submit" class="save-button">Valider</button>
            <button type="button" class="cancel-button" onclick="cancel()">Annuler</button>
        </div>
        <div class="form-message" id="form-message"></div>
    </form>
</div>



{% endblock content %}